- hosts: localhost
  become: true
  gather_facts: false
  tasks:
  - name: Deploy the service
    k8s:
      kubeconfig: /var/lib/jenkins/.kube/config
      state: present
      definition: "{{ lookup('template', 'service.yaml') | from_yaml }}"
      validate_certs: no
      namespace: default

  - name: Deploy the application
    k8s:
      kubeconfig: /var/lib/jenkins/.kube/config
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', 'deployment.yaml') | from_yaml }}"
